Get https://cloudfunction-fmfwhcdqdffafaca.francecentral-01.azurewebsites.net/api/HelloWorld

###

Get https://cloudfunction-fmfwhcdqdffafaca.francecentral-01.azurewebsites.net/api/calculator/5/10

###

GET http://localhost:7071/api/calculator/4/5/add

###

GET http://localhost:7071/api/calculator/4/5/subtract

###

GET http://localhost:7071/api/calculator/4/5/multiply

###

GET http://localhost:7071/api/calculator/4/4/divide

###


POST http://localhost:7071/api/calculator
Content-Type: application/json

{
  "a": 0,
  "b": 0,
  "operation": "divide"
}